# Site settings
title: Florida Keys Resorts | The Marker Resort Key West Florida
description: Enjoy a luxurious break at Florida Keys with The Marker Key West. Book your luxury stay at The Marker Key West only on the Official hotel website!
url: "http://www.themarkerkeywest.com"

# Language settings
default_lang: 'en'
languages: ['en']

# Build settings
permalink: pretty
markdown: kramdown

exclude:
  - 'sitemap.json'
  - 'assets'

keep_files: ['assets']
rsync_copy: ['_assets']

page_gen:
  - data: 'events'
    template: 'templ-calendar-more'
    dir: 'calendar-more'
  - data: 'blog'
    template: 'templ-blog-more'
    dir: 'blog-details'
  - data: 'attractions'
    template: 'attractions-details'
    dir: 'attractions'

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - media.json
  - models.json
  - node_modules
  - old_media.json
  - package.json
  - Rakefile
  - README
  - sitemap.json
  - tmp
